export const LOAD_POPULAR_REQUEST = "popular/LOAD_POPULAR_REQUEST";
export const LOAD_POPULAR_SUCCESS = "popular/LOAD_POPULAR_SUCCESS";
export const LOAD_POPULAR_FAILURE = "popular/LOAD_POPULAR_FAILURE";

export type LoadPopularActionTypes = typeof LOAD_POPULAR_REQUEST | typeof LOAD_POPULAR_SUCCESS | typeof LOAD_POPULAR_FAILURE;
